onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /simple_tb/u_simple_cpu/clk
add wave -noupdate /simple_tb/u_simple_cpu/resetn
add wave -noupdate /simple_tb/u_simple_cpu/pc_incr
add wave -noupdate /simple_tb/u_simple_cpu/pc
add wave -noupdate /simple_tb/u_simple_cpu/instr_addr
add wave -noupdate /simple_tb/u_simple_cpu/INSTR
add wave -noupdate /simple_tb/u_simple_cpu/dmem_wren
add wave -noupdate /simple_tb/u_simple_cpu/dmem_addr
add wave -noupdate /simple_tb/u_simple_cpu/dmem_din
add wave -noupdate /simple_tb/u_simple_cpu/dmem_dout
add wave -noupdate /simple_tb/u_simple_cpu/regf_wren
add wave -noupdate /simple_tb/u_simple_cpu/regf_raddrN
add wave -noupdate /simple_tb/u_simple_cpu/regf_rdoutN
add wave -noupdate /simple_tb/u_simple_cpu/regf_raddrM
add wave -noupdate /simple_tb/u_simple_cpu/regf_rdoutM
add wave -noupdate /simple_tb/u_simple_cpu/regf_waddr
add wave -noupdate /simple_tb/u_simple_cpu/regf_wdin
add wave -noupdate /simple_tb/u_simple_cpu/phase
add wave -noupdate /simple_tb/u_simple_cpu/A
add wave -noupdate /simple_tb/u_simple_cpu/B
add wave -noupdate /simple_tb/u_simple_cpu/O
add wave -noupdate /simple_tb/u_simple_cpu/add0_sub1
add wave -noupdate /simple_tb/u_simple_cpu/u_pc/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_pc/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_pc/phase
add wave -noupdate /simple_tb/u_simple_cpu/u_pc/pc_incr
add wave -noupdate /simple_tb/u_simple_cpu/u_pc/pc
add wave -noupdate /simple_tb/u_simple_cpu/u_instr_mem/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_instr_mem/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_instr_mem/instr_addr
add wave -noupdate /simple_tb/u_simple_cpu/u_instr_mem/INSTR
add wave -noupdate /simple_tb/u_simple_cpu/u_dmem/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_dmem/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_dmem/dmem_wren
add wave -noupdate /simple_tb/u_simple_cpu/u_dmem/dmem_addr
add wave -noupdate /simple_tb/u_simple_cpu/u_dmem/dmem_din
add wave -noupdate /simple_tb/u_simple_cpu/u_dmem/dmem_dout
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_wren
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_raddrN
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_rdoutN
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_raddrM
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_rdoutM
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_waddr
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_wdin
add wave -noupdate /simple_tb/u_simple_cpu/u_phase/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_phase/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_phase/phase
add wave -noupdate /simple_tb/u_simple_cpu/u_alu/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_alu/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_alu/add0_sub1
add wave -noupdate /simple_tb/u_simple_cpu/u_alu/A
add wave -noupdate /simple_tb/u_simple_cpu/u_alu/B
add wave -noupdate /simple_tb/u_simple_cpu/u_alu/O
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/INSTR
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/phase
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/regf_rdoutN
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/regf_rdoutM
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/dmem_dout
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/O
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/regf_wren
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/regf_wdin
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/regf_raddrN
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/regf_raddrM
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/regf_waddr
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/dmem_wren
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/dmem_addr
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/dmem_din
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/pc_incr
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/add0_sub1
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/A
add wave -noupdate /simple_tb/u_simple_cpu/u_decode_ex/B
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/clk
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/resetn
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_wren
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_raddrN
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_rdoutN
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_raddrM
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_rdoutM
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_waddr
add wave -noupdate /simple_tb/u_simple_cpu/u_regfile/regf_wdin
add wave -noupdate {/simple_tb/u_simple_cpu/u_regfile/REGF[0]}
add wave -noupdate {/simple_tb/u_simple_cpu/u_regfile/REGF[1]}
add wave -noupdate {/simple_tb/u_simple_cpu/u_regfile/REGF[2]}
add wave -noupdate {/simple_tb/u_simple_cpu/u_regfile/REGF[3]}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1645 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 291
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1853 ns}
